### ISSUE TITLE
OpenAPI documentation not working on deploy

### ISSUE THREAD

**Issue by CarlosLavilla** [Arquisoft/wichat_en2a#140]
When deploying the application to the VM in the cloud, the yml file should be modified so the requests are done into the VM and not into localhost:

![Image of swagger in the deployed system](https://github.com/user-attachments/assets/83b395ed-c00b-427e-a984-c2e874bd2a66)

Otherwise we will not be able to perform the requests.

**Comment by CarlosLavilla** [comment]
If you want to view it yourself, you can access to it accessing the [application](http://79.72.56.202:8000/api-doc).

**Comment by CarlosLavilla** [comment]
The first and simplest approach is just to add the IP of the VM by hand. It is not the best approach for sure because it will not automatically change if we use a different host machine. A better approach would be to pass it via code. But for now and just to try if it works, we will try this first simple approach.

```
servers:
  - url: http://localhost:8000
    description: Gateway service (local)
  - url: http://79.72.56.202:8000
    description: Gateway service (remote)
```
